### ISSUE TITLE
subprocess.run in blastdbcmd.py (line 22)

### ISSUE THREAD

**Issue by KyleLevi** [NCBI-Hackathons/VirusFriends#6]
I'll take a deeper look at this later.

python3 src/virusfriends.py --inputs SRR3403834

Analyzing  ['SRR3403834'] using analysis.
Setup Blast DB virusdb
Traceback (most recent call last):
  File "src/virusfriends.py", line 183, in <module>
    main()
  File "src/virusfriends.py", line 174, in main
    e.setup()
  File "src/virusfriends.py", line 60, in setup
    self.check_databases()
  File "src/virusfriends.py", line 71, in check_databases
    self.dbs[i].setup(src=self.db_sources[i]['src'])
  File "/home/klevi/VirusFriends/src/../lib/blast/blastdb/database.py", line 88, in setup
    if not self.dbtool.exists(os.path.join(self.dbdir, self.title)):
  File "/home/klevi/VirusFriends/src/../lib/blast/blastdb/blastdbcmd.py", line 22, in exists
    if subprocess.run(cmd, stdout=subprocess.PIPE, bufsize=1).returncode > 0:
AttributeError: 'module' object has no attribute 'run'

**Comment by KyleLevi** [comment]
Looks like an issue with python versions. I installed VirusFriends on an image that has the default python3 as 3.4 and subprocess was changed in 3.5/3.6

https://docs.python.org/3/library/subprocess.html
