### ISSUE TITLE
Using fastq as input does not successfully execute magicblast alignment

### ISSUE THREAD

**Issue by gstarrett** [NCBI-Hackathons/VirusFriends#7]
On Ubuntu server:
Using fastq as input does not successfully execute magicblast alignment with the following error:
Traceback (most recent call last):
  File "src/virusfriends.py", line 183, in <module>
    main()
  File "src/virusfriends.py", line 178, in main
    e.screen(args.inputs, args.intype)
  File "src/virusfriends.py", line 101, in screen
    s.screen_srr(s.srr, s.virus_db.path, samfile)
TypeError: screen_srr() missing 1 required positional argument: 'samfile'

**Comment by JonathonMifsud** [comment]
Hi @gstarrett, I realize this was a while back but did you happen to find a solution to this issue? I currently have the same problem.
